// Copyright 2026 The EnvDoctor Authors
// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"bufio"
	"context"
	_ "embed"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/reswaraa/envdoctor/internal/config"
	"github.com/reswaraa/envdoctor/internal/engine"
	"github.com/reswaraa/envdoctor/internal/probes"
	"github.com/reswaraa/envdoctor/internal/recipes"
	"github.com/reswaraa/envdoctor/internal/system"
)

// bootstrapTemplate is the canonical per-repo bootstrap script
// shipped alongside this file. `envdoctor init` substitutes the
// placeholders and writes the result to ./envdoctor.
//
//go:embed bootstrap_template.sh
var bootstrapTemplate string

// defaultRepo is the GitHub release source baked into bootstraps
// generated by `envdoctor init`. Overridable via --repo for forks.
const defaultRepo = "reswaraa/envdoctor"

// platformSHAs holds the four SHA-256 digests the bootstrap pins
// for the supported (os, arch) matrix. Empty strings render as
// "" in the bootstrap, which always fails the verify step — safer
// than a half-pinned bootstrap that "works" on one platform but
// trusts unverified bytes on the others.
type platformSHAs struct {
	DarwinAmd64 string
	DarwinArm64 string
	LinuxAmd64  string
	LinuxArm64  string
}

// sumFetcher resolves the four-platform SHA-256 digest set for a
// given version tag. In production this calls fetchSumsFromGitHub;
// tests pass a stub so they don't touch the network.
type sumFetcher func(ctx context.Context, repo, version string) (platformSHAs, error)

type initOpts struct {
	force       bool
	skipScan    bool
	repo        string
	fetcher     sumFetcher
	envdoctorV  string // injected for tests (defaults to Version)
	withCI      bool
	withConfig  bool
	readmeBadge bool
}

func newInitCmd() *cobra.Command {
	f := initOpts{
		repo:       defaultRepo,
		fetcher:    fetchSumsFromGitHub,
		envdoctorV: Version,
	}
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold ./envdoctor bootstrap and .envdoctor.yaml",
		Long: `Init writes:

  ./envdoctor         a POSIX-sh bootstrap pinning a specific
                      envdoctor release by SHA-256, so any
                      contributor can run ./envdoctor scan without
                      installing anything globally.
  .envdoctor.yaml     a minimal config (schema_version + min_version)
                      that maintainers can grow into the override
                      catalog over time.

Refuses to write if the current scan has findings (run them
through ` + "`envdoctor fix`" + ` first). Refuses to overwrite existing
files unless --force.

NEVER mutates README.md or CONTRIBUTING.md — snippets you can
paste are printed to stdout at the end.`,
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runInit(cmd, f)
		},
	}
	cmd.Flags().BoolVar(&f.force, "force", false, "overwrite existing ./envdoctor and .envdoctor.yaml")
	cmd.Flags().BoolVar(&f.skipScan, "skip-scan", false, "scaffold even if the current scan has findings (dangerous; only use when intentionally pinning a broken state)")
	cmd.Flags().StringVar(&f.repo, "repo", defaultRepo, "GitHub repo owner/name baked into the bootstrap")
	cmd.Flags().BoolVar(&f.withCI, "with-ci", false, "also write .github/workflows/envdoctor.yml (PR + push-to-main scan)")
	cmd.Flags().BoolVar(&f.withConfig, "with-config", false, "scaffold a richer commented .envdoctor.yaml with override + check examples (instead of the bare minimum)")
	cmd.Flags().BoolVar(&f.readmeBadge, "readme-badge", false, "include a Markdown badge snippet in the printed README block")
	return cmd
}

func runInit(cmd *cobra.Command, opts initOpts) error {
	ctx := cmd.Context()
	stdout := cmd.OutOrStdout()
	stderr := cmd.ErrOrStderr()

	cwd, err := os.Getwd()
	if err != nil {
		return &exitErr{code: ExitCrashed, err: fmt.Errorf("resolve cwd: %w", err)}
	}
	repoRoot, err := filepath.Abs(cwd)
	if err != nil {
		return &exitErr{code: ExitCrashed, err: fmt.Errorf("abs cwd: %w", err)}
	}

	bootstrapPath := filepath.Join(repoRoot, "envdoctor")
	configPath := filepath.Join(repoRoot, config.FileName)

	if !opts.force {
		if err := refuseIfExists(bootstrapPath); err != nil {
			return &exitErr{code: ExitCrashed, err: err}
		}
		if err := refuseIfExists(configPath); err != nil {
			return &exitErr{code: ExitCrashed, err: err}
		}
	}

	if !opts.skipScan {
		if findings, scanErr := scanForInit(ctx, repoRoot); scanErr != nil {
			return &exitErr{code: ExitCrashed, err: scanErr}
		} else if findings > 0 {
			return &exitErr{code: ExitRepairable, err: fmt.Errorf(
				"%d finding(s) — run `envdoctor fix` first, or pass --skip-scan to bypass",
				findings,
			)}
		}
	}

	if opts.envdoctorV == "" || opts.envdoctorV == "dev" {
		return &exitErr{code: ExitCrashed, err: fmt.Errorf(
			"`envdoctor init` needs a released envdoctor (Version=%q); install via curl|sh first",
			opts.envdoctorV,
		)}
	}
	version := opts.envdoctorV
	if !strings.HasPrefix(version, "v") {
		version = "v" + version
	}

	writef(stderr, "envdoctor init: fetching SHA-256 digests for %s\n", version)
	sums, err := opts.fetcher(ctx, opts.repo, version)
	if err != nil {
		return &exitErr{code: ExitCrashed, err: fmt.Errorf("fetch sha256sums: %w", err)}
	}

	bootstrap := renderBootstrap(bootstrapTemplate, version, opts.repo, sums)
	if err := atomicWriteFile(bootstrapPath, []byte(bootstrap), 0o755); err != nil {
		return &exitErr{code: ExitCrashed, err: fmt.Errorf("write bootstrap: %w", err)}
	}
	writef(stderr, "  wrote %s (chmod 0755)\n", relpath(repoRoot, bootstrapPath))

	cfgBody := renderMinimalConfig(version)
	if opts.withConfig {
		cfgBody = renderCommentedConfig(version)
	}
	if err := atomicWriteFile(configPath, []byte(cfgBody), 0o644); err != nil {
		return &exitErr{code: ExitCrashed, err: fmt.Errorf("write config: %w", err)}
	}
	writef(stderr, "  wrote %s\n", relpath(repoRoot, configPath))

	if opts.withCI {
		ciDir := filepath.Join(repoRoot, ".github", "workflows")
		ciPath := filepath.Join(ciDir, "envdoctor.yml")
		if !opts.force {
			if err := refuseIfExists(ciPath); err != nil {
				return &exitErr{code: ExitCrashed, err: err}
			}
		}
		if err := os.MkdirAll(ciDir, 0o755); err != nil {
			return &exitErr{code: ExitCrashed, err: fmt.Errorf("mkdir %s: %w", ciDir, err)}
		}
		if err := atomicWriteFile(ciPath, []byte(ciWorkflow), 0o644); err != nil {
			return &exitErr{code: ExitCrashed, err: fmt.Errorf("write CI workflow: %w", err)}
		}
		writef(stderr, "  wrote %s\n", relpath(repoRoot, ciPath))
	}

	printPasteSnippets(stdout, version, opts.readmeBadge, opts.repo)
	return nil
}

// refuseIfExists is the safety lever: init refuses to clobber an
// existing bootstrap or config unless the user passed --force. A
// silent overwrite of either is exactly the surprise we don't
// want — both are committed files in the user's repo.
func refuseIfExists(path string) error {
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("%s already exists — pass --force to overwrite", filepath.Base(path))
	}
	return nil
}

// scanForInit runs the same scan path as `envdoctor scan` but
// returns just a finding count. We don't want the user committing
// a bootstrap from a broken environment; the bootstrap is supposed
// to reflect a known-good baseline.
func scanForInit(ctx context.Context, repoRoot string) (int, error) {
	facts := system.Collect()
	lib, err := recipes.DefaultLibrary()
	if err != nil {
		return 0, fmt.Errorf("load recipes: %w", err)
	}
	cfg, err := config.Load(repoRoot, Version)
	if err != nil {
		// A malformed existing config isn't a fatal init blocker —
		// the user may be about to overwrite it. Treat as zero
		// findings and let the file write proceed (with --force).
		return 0, nil
	}
	findings, _ := engine.New(BuiltinProbes(lib, cfg)).Run(ctx, probes.Input{
		RepoRoot: repoRoot,
		System:   facts,
	})
	return len(filterDisabled(findings, cfg)), nil
}

// renderBootstrap performs the placeholder substitution. The set
// of placeholders is tested in bootstrap_template_test.go.
func renderBootstrap(template, version, repo string, sums platformSHAs) string {
	return strings.NewReplacer(
		"__ENVDOCTOR_VERSION__", version,
		"__ENVDOCTOR_REPO__", repo,
		"__SHA_DARWIN_AMD64__", sums.DarwinAmd64,
		"__SHA_DARWIN_ARM64__", sums.DarwinArm64,
		"__SHA_LINUX_AMD64__", sums.LinuxAmd64,
		"__SHA_LINUX_ARM64__", sums.LinuxArm64,
	).Replace(template)
}

// renderMinimalConfig is the smallest valid .envdoctor.yaml: just
// the schema version and the min_version pin. Maintainers grow
// this over time with checks/overrides/disables; init only seeds
// the floor.
func renderMinimalConfig(version string) string {
	return fmt.Sprintf(`# .envdoctor.yaml — see https://reswaraa.github.io/envdoctor/schema/v1/config
schema_version: 1
envdoctor:
  min_version: %q
`, strings.TrimPrefix(version, "v"))
}

// renderCommentedConfig is the --with-config form: same minimal
// header followed by commented examples of every declarative
// check type, plus override and disable patterns. Inference-first
// stays intact — every example is commented out by default.
func renderCommentedConfig(version string) string {
	return fmt.Sprintf(`# .envdoctor.yaml — see https://reswaraa.github.io/envdoctor/schema/v1/config
#
# envdoctor infers most checks from the repo's manifest files
# (package.json, .nvmrc, docker-compose.yml, …). This file lets you
# *add* checks or override severity on top of that — it does not
# replace inference.

schema_version: 1

envdoctor:
  min_version: %q

# Additive checks. Each entry is a typed-list discriminator; the
# four supported types are tool_version, port_free, env_required,
# command_present. Uncomment and edit any you need.
#
# checks:
#   # Require a specific tool on PATH at a constrained version.
#   - type: tool_version
#     tool: terraform
#     constraint: ">=1.6,<2.0"
#
#   # Require a TCP port to be free at scan time.
#   - type: port_free
#     port: 5432
#
#   # Require env vars to be present (envdoctor never reads values).
#   - type: env_required
#     keys: [MY_API_KEY, MY_DB_URL]
#
#   # Require a command to be on PATH.
#   - type: command_present
#     command: kubectl

# Override individual probe outputs by ID. Useful for project-
# specific exceptions that envdoctor's defaults get wrong.
#
# overrides:
#   node-version:
#     severity: warning

# Disable specific probes entirely by ID. Use sparingly — disabling
# a probe means no contributor sees the finding it would have
# raised, regardless of host state.
#
# disable:
#   - arch-mismatch
`, strings.TrimPrefix(version, "v"))
}

// ciWorkflow is the .github/workflows/envdoctor.yml file scaffolded
// by --with-ci. The workflow invokes the per-repo bootstrap that
// envdoctor init also wrote, so PR runs use the same SHA-pinned
// binary every contributor uses locally.
const ciWorkflow = `# .github/workflows/envdoctor.yml — generated by ` + "`envdoctor init --with-ci`" + `
name: envdoctor

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: envdoctor scan
        run: ./envdoctor scan
`

// atomicWriteFile writes content to path atomically: a tempfile
// in the same directory followed by an os.Rename. Either the file
// exists in full with the right perms or it doesn't exist at all
// — never a half-written file in the user's repo. The "atomic"
// prefix avoids the name clash with writeFile() in explain_test.go.
func atomicWriteFile(path string, content []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp.*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer func() {
		// If we error out after CreateTemp, make sure we don't leave
		// the partial file behind.
		_ = os.Remove(tmpName)
	}()
	if _, err := tmp.Write(content); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpName, mode); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

// fetchSumsFromGitHub downloads
//
//	https://github.com/<repo>/releases/download/<version>/sha256sums.txt
//
// and extracts the four platform digests. The HTTP client has a
// short timeout — `envdoctor init` is interactive; a hung GitHub
// is better surfaced as "fetch sha256sums failed" than as a
// silent multi-minute wait.
func fetchSumsFromGitHub(ctx context.Context, repo, version string) (platformSHAs, error) {
	url := fmt.Sprintf("https://github.com/%s/releases/download/%s/sha256sums.txt", repo, version)
	return fetchSumsFromURL(ctx, url, strings.TrimPrefix(version, "v"))
}

func fetchSumsFromURL(ctx context.Context, url, versionNoV string) (platformSHAs, error) {
	httpClient := &http.Client{Timeout: 15 * time.Second}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return platformSHAs{}, err
	}
	resp, err := httpClient.Do(req)
	if err != nil {
		return platformSHAs{}, err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return platformSHAs{}, fmt.Errorf("GET %s: HTTP %d", url, resp.StatusCode)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return platformSHAs{}, err
	}
	return parsePlatformSums(string(body), versionNoV)
}

// parsePlatformSums reads a sha256sums.txt body (the GoReleaser
// format `<sha>  <filename>` per line) and returns the four
// platform digests for the envdoctor_<version>_<os>_<arch>.tar.gz
// archive names. A missing platform entry is an error — we don't
// ship a half-pinned bootstrap.
func parsePlatformSums(body, versionNoV string) (platformSHAs, error) {
	want := map[string]string{
		fmt.Sprintf("envdoctor_%s_darwin_amd64.tar.gz", versionNoV): "",
		fmt.Sprintf("envdoctor_%s_darwin_arm64.tar.gz", versionNoV): "",
		fmt.Sprintf("envdoctor_%s_linux_amd64.tar.gz", versionNoV):  "",
		fmt.Sprintf("envdoctor_%s_linux_arm64.tar.gz", versionNoV):  "",
	}
	s := bufio.NewScanner(strings.NewReader(body))
	for s.Scan() {
		fields := strings.Fields(s.Text())
		if len(fields) < 2 {
			continue
		}
		// GoReleaser may emit `*<file>` (BSD) or `<file>`; tolerate.
		name := strings.TrimPrefix(fields[1], "*")
		if _, ok := want[name]; ok {
			want[name] = fields[0]
		}
	}
	if err := s.Err(); err != nil {
		return platformSHAs{}, err
	}
	out := platformSHAs{
		DarwinAmd64: want[fmt.Sprintf("envdoctor_%s_darwin_amd64.tar.gz", versionNoV)],
		DarwinArm64: want[fmt.Sprintf("envdoctor_%s_darwin_arm64.tar.gz", versionNoV)],
		LinuxAmd64:  want[fmt.Sprintf("envdoctor_%s_linux_amd64.tar.gz", versionNoV)],
		LinuxArm64:  want[fmt.Sprintf("envdoctor_%s_linux_arm64.tar.gz", versionNoV)],
	}
	var missing []string
	for k, v := range want {
		if v == "" {
			missing = append(missing, k)
		}
	}
	if len(missing) > 0 {
		return platformSHAs{}, fmt.Errorf("sha256sums.txt missing entries: %s", strings.Join(missing, ", "))
	}
	return out, nil
}

func relpath(base, target string) string {
	if r, err := filepath.Rel(base, target); err == nil {
		return "./" + r
	}
	return target
}

// printPasteSnippets writes the README and CONTRIBUTING blurbs
// to stdout. We never mutate the user's docs — they paste these
// where it makes sense for their project. When badge=true the
// README block leads with a Markdown badge snippet.
func printPasteSnippets(w io.Writer, version string, badge bool, repo string) {
	writeln(w, "")
	writeln(w, "─── README snippet (paste under Setup / Contributing) ───")
	writeln(w, "")
	if badge {
		// The badge SVG is served from the docs site (GitHub Pages,
		// no server). The shape is intentionally generic — a
		// per-repo dynamic badge would require a server, which
		// envdoctor deliberately avoids.
		writef(w, "[![envdoctor scan](https://reswaraa.github.io/envdoctor/badge.svg)](https://reswaraa.github.io/envdoctor/repo/%s)\n\n", repo)
	}
	writef(w, `Run ./envdoctor scan before running tests.
This pins envdoctor %s and verifies the binary by SHA-256 — no
global install required.

    ./envdoctor scan       # report environment problems
    ./envdoctor fix        # walk through repairs interactively

`, version)
	writeln(w, "─── CONTRIBUTING snippet ───")
	writeln(w, "")
	writef(w, `If `+"`./envdoctor scan`"+` reports findings, try `+"`./envdoctor fix`"+`
to walk through repair commands. Open an issue if a finding has
no recipe — that's the signal envdoctor needs to grow its library.

`)
}
