#!/bin/sh
# Copyright 2026 The EnvDoctor Authors
# SPDX-License-Identifier: Apache-2.0
#
# ./envdoctor — committable bootstrap for this repo. Generated by
# `envdoctor init`; safe to read top-to-bottom and commit as-is.
#
# What it does:
#   1. Detects OS+arch.
#   2. Reuses the cached binary at
#      ~/.cache/envdoctor/versions/<version>/<os>_<arch>/envdoctor
#      if present.
#   3. Otherwise downloads the release tarball pinned below from
#      GitHub Releases, verifies its SHA-256 against the digest
#      baked in at `init` time, extracts to the cache, and execs
#      the binary with all your arguments.
#
# Pinned in-tree so a contributor can clone + run ./envdoctor scan
# without trusting whatever sha256sums.txt is being served today.
# Updating the pin requires a new `envdoctor init` (or `envdoctor
# upgrade --bootstrap`).

set -eu

# ---- pinned by `envdoctor init` (do not hand-edit) --------------
ENVDOCTOR_VERSION="__ENVDOCTOR_VERSION__"
ENVDOCTOR_REPO="__ENVDOCTOR_REPO__"
SHA_DARWIN_AMD64="__SHA_DARWIN_AMD64__"
SHA_DARWIN_ARM64="__SHA_DARWIN_ARM64__"
SHA_LINUX_AMD64="__SHA_LINUX_AMD64__"
SHA_LINUX_ARM64="__SHA_LINUX_ARM64__"
# Override the release host in tests; defaults to github.com.
ENVDOCTOR_BASE_URL="${ENVDOCTOR_BASE_URL:-https://github.com}"
# -----------------------------------------------------------------

case "$(uname -s)" in
	Darwin) os=darwin ;;
	Linux)  os=linux ;;
	*) echo "envdoctor: unsupported OS $(uname -s)" >&2; exit 1 ;;
esac
case "$(uname -m)" in
	x86_64|amd64) arch=amd64 ;;
	arm64|aarch64) arch=arm64 ;;
	*) echo "envdoctor: unsupported arch $(uname -m)" >&2; exit 1 ;;
esac

case "${os}_${arch}" in
	darwin_amd64) expected="$SHA_DARWIN_AMD64" ;;
	darwin_arm64) expected="$SHA_DARWIN_ARM64" ;;
	linux_amd64)  expected="$SHA_LINUX_AMD64" ;;
	linux_arm64)  expected="$SHA_LINUX_ARM64" ;;
esac

cache_dir="${HOME}/.cache/envdoctor/versions/${ENVDOCTOR_VERSION}/${os}_${arch}"
bin="${cache_dir}/envdoctor"

if [ ! -x "$bin" ]; then
	version_no_v="${ENVDOCTOR_VERSION#v}"
	tarball="envdoctor_${version_no_v}_${os}_${arch}.tar.gz"
	url="${ENVDOCTOR_BASE_URL}/${ENVDOCTOR_REPO}/releases/download/${ENVDOCTOR_VERSION}/${tarball}"

	tmp=$(mktemp -d "${TMPDIR:-/tmp}/envdoctor.XXXXXX")
	trap 'rm -rf "$tmp"' EXIT INT TERM

	if command -v curl >/dev/null 2>&1; then
		curl -fsSL "$url" -o "$tmp/$tarball"
	elif command -v wget >/dev/null 2>&1; then
		wget -q "$url" -O "$tmp/$tarball"
	else
		echo 'envdoctor: need curl or wget on PATH' >&2
		exit 1
	fi

	if command -v sha256sum >/dev/null 2>&1; then
		actual=$(sha256sum "$tmp/$tarball" | awk '{print $1}')
	elif command -v shasum >/dev/null 2>&1; then
		actual=$(shasum -a 256 "$tmp/$tarball" | awk '{print $1}')
	else
		echo 'envdoctor: need sha256sum or shasum on PATH' >&2
		exit 1
	fi

	if [ "$expected" != "$actual" ]; then
		printf 'envdoctor: SHA-256 mismatch on %s\n  expected: %s\n  actual:   %s\n' \
			"$tarball" "$expected" "$actual" >&2
		exit 1
	fi

	mkdir -p "$cache_dir"
	tar -C "$cache_dir" -xzf "$tmp/$tarball"
fi

exec "$bin" "$@"
